development:
  adapter: postgresql
  encoding: unicode
  database: sigdiv_development
  pool: 5
  username: sigdiv
  password: passwordDB

production:
  adapter: postgresql
  encoding: unicode
  database: sigdiv_production
  pool: 5
  username: sigdiv
  password: passwordDB

test:
  adapter: postgresql
  encoding: unicode
  database: sigdiv_test
  pool: 5
  username: sigdiv
  password: passwordDB