development:
  adapter: postgresql
  encoding: unicode
  database: sadp_development
  pool: 5
  username: sadp
  password: passwordDB

test:
  adapter: postgresql
  encoding: unicode
  database: sadp_test
  pool: 5
  username: sadp
  password: passwordDB